CREATE TABLE Product (
  ID INTEGER AUTO_INCREMENT PRIMARY KEY,
  Name VARCHAR(50) NOT NULL,
  Description VARCHAR(100) NOT NULL
);

CREATE TABLE Supplier (
  ID INTEGER AUTO_INCREMENT PRIMARY KEY,
  Name VARCHAR(50) NOT NULL
);

CREATE TABLE Orders (
  ID INTEGER AUTO_INCREMENT PRIMARY KEY,
  ProductId INTEGER NULL,
  SupplierId INTEGER NULL,
  Date DATE,
  Quantity INTEGER,
  TotalBill INTEGER,
  CONSTRAINT fk_product FOREIGN KEY (ProductId) REFERENCES Product(ID) ON DELETE SET NULL,
  CONSTRAINT fk_supplier FOREIGN KEY (SupplierId) REFERENCES Supplier(ID) ON DELETE SET NULL
);